[package]
edition      = "2024"
name         = "esp-rust"
rust-version = "1.95"
version      = "0.1.0"

[[bin]]
name = "esp-rust"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.2.2", features = ["defmt", "esp32c6", "unstable"] }


defmt                  = "1.0.1"
esp-bootloader-esp-idf = { version = "0.6.0", features = ["defmt", "esp32c6"] }

critical-section = "1.2.0"
esp-backtrace = { version = "0.20.0", features = [
  "defmt",
  "esp32c6",
  "panic-handler",
] }
esp-println = { version = "0.18.0", features = ["defmt-espflash", "esp32c6"] }
esp-hal-smartled = "0.18.0"
smart-leds = "0.4.0"
mpu6050 = "0.1.6"
embedded-hal-compat = "0.13"
embedded-hal-02 = { package = "embedded-hal", version = "0.2.7" }
heapless = "0.9.3"
esp-alloc = { version = "0.11.0", features = ["esp32c6"] }

embassy-executor = "0.10.0"
embassy-time = "0.5.0"
esp-rtos = { version = "0.4", features = ["esp32c6", "embassy", "defmt", "esp-radio", "esp-alloc"] }
embassy-sync = "0.8"
static_cell = "2"
embassy-net = { version = "0.9", features = ["dhcpv4", "medium-ethernet", "tcp", "defmt"] }
esp-radio = { version = "=1.0.0-beta.1", features = ["esp32c6", "wifi", "defmt"] }
embedded-websocket = { version = "0.9.5", default-features = false }
embedded-io-async = { version = "0.7", default-features = false }
embassy-futures = "0.1.2"
serde = { version = "1", default-features = false, features = ["derive"] }
serde-json-core = "0.6"


# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
