[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "julilili42", email = "Julian-jurcevic-2000@web.de" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "matplotlib>=3.11.2",
    "uvicorn>=0.54.0",
    "websockets>=17.1",
]

[project.scripts]
server = "server:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
